import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Product from '../components/ProductCard';
import SearchBar from '../components/SearchBar';
import { useState } from 'react';

function Home(props) {
  const { data, categories } = props;
  const [products, setProducts] = useState(data);

  const fetchData = (qSearch, qCateg) => {
    const querySearch = qSearch ? `search=${qSearch}` : '';
    const queryCategories = qCateg ? `categories=${qCateg}` : '';
    fetch(`/api?${querySearch}&${queryCategories}`).then(data => data.json()).then(data => {
      setProducts(data.data)
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div>
          <SearchBar onSearchHandler={fetchData} categories={categories}/>
        </div>
        <div className={styles.grid}>
          {products.map(product => {
            return (
              <div key={product.productId} className={styles.productContainer}>
                <Product
                  id={product.id}
                  image={product.image}
                  name={product.name}
                  categories={product.categories}
                  price={product.price}
                  brand={product.brand}
                />
              </div>
            )
          })}
        </div>
      </main>

      {/*<footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>*/}
    </div>
  )
}

export async function getStaticProps() {
  let data = await fetch('http://localhost:3000/api');
  data = (await data.json()).data
  const categories = []
  data.forEach(item => {
    if (!categories.includes(item.categories)) {
      categories.push(item.categories)
    }
  })

  return {
    props: { data, categories }
  };
}

export default Home
